### PR TITLE
Isrs 44 log in isrs as admin

### PR DESCRIPTION
**Pull request by fewdw**
Added functionality for admin authentication

### CODE REVIEW

**Review by FrancisShehata — APPROVED** [review]
Great job fred! The authentication for the admin login works great. Next time you should commit more often you did a lot of work and you have little commits so next time commit every line of code u change!

**Review by Alexssuto — APPROVED** [review]
Authentication looks good, im not really sure if youre storing the information anywhere or is auth0 taking care of it> Either way, try to make sure its secure and that it works for admin properly.

**Comment by VictorSsuto** [comment]
Sorry i didnt approve of this PR since you showed it to me but I'm leaving a comment since i am not sure how to use it properly could you give me a quick guide?

**Comment by fewdw** [comment]
> Sorry i didnt approve of this PR since you showed it to me but I'm leaving a comment since i am not sure how to use it properly could you give me a quick guide?

Make sure you use: admin@admin.com and admin as credentials. You can also create credentials in the admin panel. For now only admin authentication work so all staff and employer paths are still available

**Pull request merged**
