### PR TITLE
Bug/isrs fix css

### PR DESCRIPTION
**Pull request by VictorSsuto**
Fixed the css

### CODE REVIEW

**Review by fewdw — APPROVED** [review]
Good. Look on jira I just added a bug in the staff filter list, take a look at that next

**Review by FrancisShehata — APPROVED** [review]
great work vic, glad you fixed that weird bug that we encountered

**Review by Alexssuto — APPROVED** [review]
Thats good, I got to see the changes in real life.

**Comment by VictorSsuto** [comment]
Fixed the merge issues

**Pull request closed without merging**
