### PR TITLE
Feat/isrs 46 employer login

### PR DESCRIPTION
**Pull request by FrancisShehata**
added login for employer and refined all login pages to have the same styling

### CODE REVIEW

**Review by VictorSsuto — COMMENTED** [review]
I wont approve it yet but could u show us the new UI compared to the old one?  I will approve it afterwards

**Comment by FrancisShehata** [comment]
thank you for letting me know ill put a before an after picture right away!

**Comment by FrancisShehata** [comment]
before: 
image

After:
image

there you go

**Review by fewdw — APPROVED** [review]
great changes, matches the figma perfectly

**Pull request merged**
