### PR TITLE
Bug isrs 94 fix the back button 

### PR DESCRIPTION
**Pull request by VictorSsuto**
Back buttons now have an on hover and padding with color. 
image

### CODE REVIEW

**Comment by VictorSsuto** [comment]
These changes made it so that some other links have the same styling! Please create other bug pr to fix it

**Review by Alexssuto — CHANGES_REQUESTED** [review]
So from what I understand you fixed something in the ui but you didn't show proof! I'm going to have to request changes until you can provide proof. Thanks

**Review by FrancisShehata — APPROVED** [review]
great work vic ,you fixed the changes as our supervisor requested

**Review by fewdw — APPROVED** [review]
msg me on discord so i can explain to implement i18n

**Comment by VictorSsuto** [comment]
> So from what I understand you fixed something in the ui but you didn't show proof! I'm going to have to request changes until you can provide proof. Thanks

Okay let me update it

**Pull request closed without merging**
