### PR TITLE
Feat/ ISRS 6 post fuctionality frontend

### PR DESCRIPTION
**Pull request by FrancisShehata**
**Add button working for admin:** 
image

**Posting a new student working for admin:**
image

image

**Add button working for staff:**
image

**Posting a new student working for staff:**
image

image

### CODE REVIEW

**Comment by fewdw** [comment]
nice work

**Comment by VictorSsuto** [comment]
Great work francis good job on implementing it and adding styling that matches the figma

**Comment by Alexssuto** [comment]
Nice job on having the proper css as well. The programming languages look a little weird, but I suspect it's because they are in an array. I will help you take a look at it later.

**Review by VictorSsuto — APPROVED** [review]
Good job on doing good styling

**Review by fewdw — APPROVED** [review]
Good job on implementing a guide for adding a student

**Review by Alexssuto — APPROVED** [review]
We will take care of the programming language being an array hence the weird format on the UI. Or else, the post was well implemented and you made sure to check the proper css.

**Pull request merged**
