### PR TITLE
Feat/isrs 24 put functionality frontend

### PR DESCRIPTION
**Pull request by Alexssuto**
In this pull request, I had to fix the PUT method as it was still bugging a lot on me. I was also required to connect it to the front end so I can update.
Here is the POV from the admin perspective before it'sedited.
image
Here is the after.
image
Here is the POV from the staff perspective it's edited.
image
Here is the after.
image

### CODE REVIEW

**Comment by fewdw** [comment]
seems like the styling for the form is a little bit off, good job implementing edit though!

**Review by fewdw — APPROVED** [review]
Good Additions!

**Review by VictorSsuto — APPROVED** [review]
Great job on making the put work. It follows the figma

**Review by FrancisShehata — APPROVED** [review]
Great implementation Alex! one tip for next time you should follow the figma template for next time

**Pull request merged**
